### ISSUE TITLE
[feat] 도랑이 꾸미기 api

### ISSUE THREAD

**Issue by choiseoji** [Jeju-Dorang/Backend#34]
### Description
- 업적 달성하면 아이템 획득
- 현재 유저가 획득한 아이템 리스트 반환
- backgroundImage, petImage, itemImage 세 리스트로 나눠서 반환

### Todo
- [x] 회원가입하면 캐릭터 생성 + 유저에게 아이템 모두 지급 (status로 소유하지 않음을 표시)
- [x] 업적 달성하면 아직 얻지 못한 아이템 중 랜덤으로 하나  지급
- [x] /character/items 요청 들어오면 얻은 아이템 리스트 반환
