### ISSUE TITLE
[feat] 업적, 스트릭 처리

### ISSUE THREAD

**Issue by choiseoji** [Jeju-Dorang/Backend#60]
### Description

- 도랑이 놀거리 추천 페이지에 업적 id가 필요함
- isAchievement를 빼고 업적 id가 0 일때 일반 일기로 처리
- 스트릭 반환 제대로 안됨
- 도랑이 아이템 저장하는 api 추가

### Todo

- [x] 도랑이 놀거리 추천 페이지에서 achievementId 반환
- [x]  일기 requestDto에서 isAchievement 빼기 
- [x] achievementId가 0 일때 일반 일기로 처리
- [x] 스트릭 pase format 제대로
- [x] 도랑이 아이템 장착 api 추가
